name: Meta Bot Twice Daily

on:
  schedule:
    - cron: '0 8,20 * * *'  # 8 AM and 8 PM UTC
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache last_meta.json
        uses: actions/cache@v3
        with:
          path: last_meta.json
          key: meta-${{ github.run_id }}
          restore-keys: |
            meta-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: python scrape.py

