name: Meta Bot Twice Daily

on:
  schedule:
    - cron: '0 8,20 * * *'  # 8 AM and 8 PM UTC
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore meta cache
        uses: actions/cache@v3
        with:
          path: last_meta.json
          key: meta-cache

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: python scrape.py

      - name: Save updated meta
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: last-meta
          path: last_meta.json
